name: SayHello

on:
  push:
      branches:
      - main
      - develop


jobs:
  welcome:
      runs-on: ubuntu-latest

      steps:
        - name: Download your code
          uses: actions/checkout@v2

        - name: SaySomething
          run: echo "hello world"

  hello-branches:
      runs-on: ubuntu-latest

      steps:
        - name: Download your code
          uses: actions/checkout@v2

        - name: Verify develop branch
          if : ${{ github.ref == 'refs/heads/develop'}}
          run: echo "hello develop"
          
        - name: verify main branch
          if: ${{ github.ref == 'refs/heads/main'}}
          run: echo "hello main"
