name: SayHello

on:
  push:
      branches:
      - main


jobs:
  welcome:
      runs-on: ubuntu-latest

      steps:
        - name: Download your code
          uses: actions/checkout@v2

        - name: SaySomething
          run: echo "hello world"
        
